name: Unit Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build --verbose

  tests:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Output dir
      run: mkdir Out
    - name: Run tests
      run: swift test
    - name: Clean up
      run: rm -rf Out
